language: node_js

node_js:
    - "0.12"

install:
    - npm i

env:
    matrix:
        - API=--api=mock
        - API=--api=web
        - DEBUG=--debug
        - DEBUG=
script:
    - gulp $API $DEBUG
    - gulp eslint
