language: node_js

node_js:
    - "0.12"

install:
    - npm i

env:
    - OPTIONS='--api=mock'
    - OPTIONS='--api=mock --debug'
    - OPTIONS='--api=web'
    - OPTIONS='--api=web --debug'

script:
    - gulp $OPTIONS
    - gulp eslint
