language: node_js

branches:
  only:
    - master

node_js:
    - "14"
    - "15"

install:
    - npm i

script:
    - npm run lint
    - API=mock npm run build -- --mode=production
    - API=web npm run build -- --mode=production
